config/routes.rb
HomeApp::Application.routes.draw do
  get "static_pages/home"
  get "static_pages/help"
  root 'static_pages#home'
  resources :password_generator do
    member do
      get :new
      post :create
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/password_generator_controller.rb
class PasswordGeneratorController < ApplicationController

	def create
		words = File.readlines(File.join(Rails.root, 'config', 'words.txt'))
		@password = ''
		@indices = []

		#Get one word out so that we can use alliteration
		word = words[rand(words.count)].strip

		if params[:password][:alliteration] == "1"
			words.each { |word| word.chop! }
			words = words.join(' ').scan(/\b[#{word[0]}]\w*\b/)
		end

		params[:password][:word_count].to_i.times do

			puts params[:password]
			if params[:password][:numbers_for_letters] == "1"
				word.gsub! 'o', '0'
				word.gsub! 'i', '1'
				word.gsub! 'z', '2'
				word.gsub! 'e', '3'
				word.gsub! 'a', '4'
				word.gsub! 's', '5'
				word.gsub! 't', '7'
				word.gsub! 'b', '8'
				word.gsub! 'g', '9'
			end

			if params[:password][:common_substitutions] == "1"
				word.gsub! 'i', '!'
				word.gsub! 'i', '1'
				word.gsub! 'a', '@'
				word.gsub! 'e', '#'
				word.gsub! '3', '#'
				word.gsub! 's', '$'
				word.gsub! '5', '$'
				word.gsub! 'x', '*'
			end
			
			if params[:password][:camel_case] == "1"
				word.capitalize!
			end
			
			if params[:password][:keep_spaces] == "1"
				if @password.length > 1
					@indices.push @password.length + 1
					@password = @password + " "
				else
					@indices.push 0
				end
			else
					@indices.push @password.length
			end

			@password = @password + word

			word = words[rand(words.count)].strip
		end

		if params[:password][:expires_in_three_months] == "1"
			time = Time.now + 3.months
			@password += time.strftime('%m%Y')
		end

		puts @password

		respond_to do |format|
			format.js
		end
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
	def full_title(page_title)
		base_title = 'Jonathan Franke\'s App'
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/password_generator_helper.rb
module PasswordGeneratorHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">TODO: put the link here</a>
    by Jonathan Frankel
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#'%></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
 <header class="navbar navbar-fixed-top navbar-inverse" role="navigation">
      <div class="navbar-inner">
        <div class="container-fluid">
          <%= link_to "Home App", root_path, id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Home",    root_path %></li>
                <li id="fat-menu" class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Utilities <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Password Generator", new_password_generator_path %></li>
                  </ul>
                </li>
            </ul>
          </nav>
        </div>
      </div>
    </header>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  <%= render '/layouts/shim' %>
  
  </head>
  <body>
  <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag :div, value, class: "alert alert-#{key}" %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/password_generator/create.js.erb
$('#password_input').val("<%= @password %>")
$('#indices').html("<%= @indices.map(&:inspect).join(',') %>")

app/views/password_generator/new.html.erb
<% provide(:title, "Generate Password") %>
<h1>Generate Password</h1>

<%= form_for :password, url: password_generator_path,
		remote: true, html: { class: "form-horizontal" } do |f| %>

    <fieldset>
      <legend>Password parameters</legend>
      <div class="control-group">
        <label class="control-label" for="password_word_count">Word count</label>
        <div class="controls">
					<%= f.select :word_count, 1..5 %>
				</div>
			</div>

			<div class="control-group">
				<label class="control-label" for="password_camel_case">Camel Case</label>
				<div class="controls">
	        <label class="checkbox">
						<%= f.check_box :camel_case %>
					</label>
				</div>
			</div>

			<div class="control-group">
				<label class="control-label" for="password_numbers_for_letters">Number for Letters</label>
				<div class="controls">
	        <label class="checkbox">
						<%= f.check_box :numbers_for_letters %>
					</label>
				</div>
			</div>

			<div class="control-group">
				<label class="control-label" for="password_common_substitutions">Common Substitutions</label>
				<div class="controls">
	        <label class="checkbox">
						<%= f.check_box :common_substitutions %>
					</label>
				</div>
			</div>

			<div class="control-group">
				<label class="control-label" for="password_keep_spaces">Keep Spaces</label>
				<div class="controls">
	        <label class="checkbox">
						<%= f.check_box :keep_spaces %>
					</label>
				</div>
			</div>

			<div class="control-group">
				<label class="control-label" for="password_alliteration">Alliteration</label>
				<div class="controls">
	        <label class="checkbox">
						<%= f.check_box :alliteration %>
					</label>
				</div>
			</div>

			<div class="control-group">
				<label class="control-label" for="password_expires_in_three_months">Expires in 3 Months</label>
				<div class="controls">
	        <label class="checkbox" id="password_expires_in_three_months_inner_label">
						<%= f.check_box :expires_in_three_months %>
					</label>
				</div>
			</div>


      <div class="form-actions">
				<%= f.submit "Generate", class: "btn btn-primary" %>
      </div>

      <div id="indices">
      </div>

      <label class="control-label" for="password_input">Text input</label>  
          <div class="controls">  
            <input type="text" class="input-xlarge" id="password_input">
          </div>  
    </fieldset>
<% end %>

app/views/static_pages/_else_if_not_signed_in.html.erb
<div class="center hero-unit">
  <h1>Welcome Home</h1>
  <h2>
  	TODO: Put in a nicer heading
  </h2>
  <%= link_to "Sign up now!", '#', class: "btn btn-large btn-primary" %>
</div>

app/views/static_pages/_if_signed_in.html.erb
<div class="row">
  <aside class="span4">
    <section>
      <%= render 'shared/user_info' %>
    </section>
    <section>
      <%= render 'shared/stats' %>
    </section>
    <section>
      <%= render 'shared/micropost_form' %>
    </section>
  </aside>
  <div class="span8">
    <h3>Micropost Feed</h3>
    <%= render 'shared/feed' %>
  </div>
</div>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>

<h1>About Us</h1>
	<p>
	  The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
	  is a project to make a book and screencasts to teach web development
	  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
	  is the sample application for the tutorial.
	</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>

<h1>Contact</h1>
	<p>
	  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/contact">contact page</a>.	</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
  <%= render 'static_pages/else_if_not_signed_in' %>